# Generated by Django 5.2.1 on 2025-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('card', 'Credit/Debit Card'), ('bdo', 'BDO Bank Transfer')], max_length=10),
        ),
    ]
